import { Language } from '@/Components/Language'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { useLang } from '@/store/lang'
import { LangEnum } from '@/lang/lang'

const english = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const lang = useLang.getState().lang
  return (
    <html dir={lang === "english" ? "ltr" : "rtl"} lang="en">
      <body className={lang === LangEnum.EN ? english.className : "persian"}>
        {children}
        <Language/>
        </body>
    </html>
  )
}
