
import { Language } from '@/Components/Language'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {notFound} from 'next/navigation';
 
const locales = ['en', 'fa'];

const english = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'My Personal NoteBook',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,params:{locale}
}: {
  children: React.ReactNode,params:any
}) {
  const isValidLocale = locales.some((cur) => cur === locale);
  if (!isValidLocale) notFound();
  return (
    <html  lang={locale} dir={locale === "en" ? 'ltr' : 'rtl'} >
      <body className={english.className} style={{fontFamily: locale === 'fa' ? 'var(--persian)' : ''}}>
        {children}
        <Language/>
        </body>
    </html>
  )
}
