
import { Language } from '@/Components/Language'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { useLang } from '@/store/lang'
import { LangEnum } from '@/lang/lang'
import {useLocale} from 'next-intl';
import {notFound} from 'next/navigation';
 
const locales = ['en', 'de'];

const english = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,params:{locale}
}: {
  children: React.ReactNode,params:any
}) {
  const isValidLocale = locales.some((cur) => cur === locale);
  if (!isValidLocale) notFound();
  return (
    <html  >
      <body>
        {children}
        <Language/>
        </body>
    </html>
  )
}
